name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          node_version: 16
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
          run_install: true
      - name: production build
        run: pnpm run build
      - name: install Lighthouse cli
        run: |
          pnpm add @lhci/cli@0.8.x
      - name: run Lighthouse cli
        id: lhci
        run: |
          mkdir dist
          touch dist/autorun.txt
          pnpx lhci autorun | grep 'storage.googleapis.com' > ./dist/autorun.txt
          report_url=$(cat ./dist/autorun.txt)
          echo $report_url
          echo "::set-output name=report_url::$report_url"
        continue-on-error: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: json to markdown
        uses: ./.github/actions/lighthouse
        id: parse
        with:
          json-file-path: .lighthouseci/assertion-results.json
          report-url: ${{ steps.lhci.outputs.report_url }}
      - name: post comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./result-markdown.md "${URL}"
