name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.3.1
        with:
          node-version-file: .tool-versions
      - name: Setup GitHub App
        id: bot
        uses: re-taro/actions/gen-installation-token@v3.3.1
        with:
          app_id: ${{ secrets.APP_ID}}
          private_key: ${{ secrets.PRIVATE_KEY}}
      - name: Create Release Pull Request
        uses: changesets/action@v1.4.5
        with:
          publish: pnpm wrangler d1 migrations apply portfolio && pnpm build && pnpm wrangler pages publish ./public
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"
