name: Sync Renovate changeset
on:
  pull_request_target:
    paths:
      - "**/pnpm-lock.yaml"

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref}}
      - name: Setup GitHub App
        id: bot
        uses: re-taro/actions/gen-access-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID}}
          private_key: ${{ secrets.PRIVATE_KEY}}
      - name: Generate changesets
        uses: re-taro/actions/sync-renovate-changesets@v2.2.0
        with:
          token: ${{ steps.bot.outputs.token }}
