name: Sync Renovate changeset
on:
  pull_request_target:
    paths:
      - "**/pnpm-lock.yaml"

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref}}
      - name: Generate changesets
        uses: re-taro/actions/sync-renovate-changesets@v2.0.0
